command = '/opt/compteur_gase/venv/bin/gunicorn'
pythonpath = '/opt/compteur_gase'
workers = 4
user = 'compteur_gase'
bind = 'unix:/opt/compteur_gase/sock'
pid = '/run/gunicorn/compteur_gase-pid'
errorlog = '/var/log/compteur_gase/error.log'
accesslog = '/var/log/compteur_gase/access.log'
access_log_format = '%({X-Real-IP}i)s %({X-Forwarded-For}i)s %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'
loglevel = 'warning'
capture_output = True
