# Generated by Django 2.1.7 on 2019-03-15 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Catégorie',
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Adresse')),
                ('comment', models.TextField(blank=True)),
                ('account', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Foyer',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tel', models.CharField(blank=True, max_length=200)),
                ('foyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Household', verbose_name='Foyer')),
            ],
            options={
                'verbose_name': 'Membre',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Opération',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('pwyw', models.BooleanField(default=False, verbose_name='Prix libre')),
                ('vrac', models.BooleanField(verbose_name='Vrac')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('comment', models.TextField(blank=True, verbose_name='Comentaire')),
                ('stock', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Stock')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
            },
        ),
        migrations.CreateModel(
            name='AchatOp',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Operation')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Household')),
            ],
            bases=('base.operation',),
        ),
        migrations.CreateModel(
            name='ApproCompteOp',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Operation')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Household')),
            ],
            bases=('base.operation',),
        ),
        migrations.CreateModel(
            name='ApproStockOp',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Operation')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
            ],
            bases=('base.operation',),
        ),
        migrations.CreateModel(
            name='InventoryOp',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Operation')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
            ],
            bases=('base.operation',),
        ),
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Provider', verbose_name='Fournisseur'),
        ),
        migrations.AddField(
            model_name='product',
            name='referent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Member', verbose_name='Référent'),
        ),
        migrations.AddField(
            model_name='inventoryop',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Product'),
        ),
        migrations.AddField(
            model_name='approstockop',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Product'),
        ),
        migrations.AddField(
            model_name='achatop',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Product'),
        ),
    ]
