# Generated by Django 2.1.7 on 2019-06-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='pluralize',
            field=models.BooleanField(default=False, help_text="Ajouter un 's' au pluriel (par ex. 4 sachets mais 4 kg)", verbose_name='Plurieliser ?'),
        ),
    ]
