# Generated by Django 2.1.7 on 2019-03-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190315_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='receipt',
            field=models.BooleanField(default=True),
        ),
    ]
