# Generated by Django 2.2.6 on 2019-10-20 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20191020_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localsettings',
            options={'verbose_name': 'Réglages divers', 'verbose_name_plural': 'Réglages divers'},
        ),
    ]
