# Generated by Django 2.2.6 on 2019-10-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20191020_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='localsettings',
            name='mail_protocole',
            field=models.CharField(choices=[('no', 'Pas de chiffrement'), ('tls', 'Utiliser TLS'), ('ssl', 'Utiliser SSL')], default='no', max_length=100, verbose_name="Protocole utilisé pour l'envoie de mails."),
        ),
        migrations.AddField(
            model_name='localsettings',
            name='mail_timeout',
            field=models.IntegerField(default=4, verbose_name="Timeout pour l'envoi de mail."),
        ),
        migrations.AlterField(
            model_name='localsettings',
            name='mail_host',
            field=models.CharField(default='xxx', help_text='Exemple : smtp.titi.com.', max_length=50, verbose_name="Hebergeur pour l'envoi des mails."),
        ),
        migrations.AlterField(
            model_name='localsettings',
            name='mail_port',
            field=models.IntegerField(default=465, help_text='Exemple : 25 (sans chiffrement), 465 (chiffrement implicite, SSL), 587 (chiffrement explicite, TLS).', verbose_name="Port smtp pour l'envoi des mails."),
        ),
    ]
