# Generated by Django 2.2.6 on 2019-10-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20191022_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='localsettings',
            name='use_exports',
            field=models.BooleanField(default=True, help_text="Exports de l'historique d'achat et de la liste des produits.", verbose_name='Utiliser les exports ?'),
        ),
    ]
