# Generated by Django 2.1.7 on 2019-03-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20190323_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approcompteop',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
