# Generated by Django 2.1.7 on 2019-03-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20190323_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_account', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Seuil en dessous duquel on ne peut plus faire d'achat")),
            ],
            options={
                'verbose_name': 'Réglages divers',
            },
        ),
    ]
