# Generated by Django 2.1.7 on 2019-03-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_localsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='stock_alert',
            field=models.BooleanField(default=True, verbose_name='Recevoir les alertes stock par mail ? (uniquement pour les référents produit)'),
        ),
        migrations.AlterField(
            model_name='localsettings',
            name='min_account',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Seuil en dessous duquel on ne peut plus faire d'achat"),
        ),
    ]
