# Generated by Django 2.2.6 on 2020-01-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20191123_0449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Catégorie'},
        ),
        migrations.AlterModelOptions(
            name='household',
            options={'ordering': ['name'], 'verbose_name': 'Foyer'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['name'], 'verbose_name': 'Membre'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Produit'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['name'], 'verbose_name': 'Fournisseur'},
        ),
        migrations.AddField(
            model_name='localsettings',
            name='mail_from',
            field=models.CharField(default='tata@titi.com', help_text='Exemple : tata@titi.com.', max_length=100, verbose_name="Expéditeur pour l'envoi des mails."),
        ),
        migrations.AlterField(
            model_name='localsettings',
            name='mail_username',
            field=models.CharField(default='tata', help_text='Exemple : tata.', max_length=100, verbose_name="Nom d'utilisateur pour l'envoi des mails."),
        ),
    ]
