# Generated by Django 2.2.6 on 2020-01-04 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20200104_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localsettings',
            name='use_favicon',
        ),
    ]
