# Generated by Django 2.2.6 on 2020-01-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_localsettings_use_favicon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['name'], 'verbose_name': 'Unité'},
        ),
        migrations.AlterField(
            model_name='approcompteop',
            name='kind',
            field=models.CharField(choices=[('cash', 'Espèces'), ('cheque', 'Chèque'), ('cancellation', 'Annulation/Correction'), ('repayment', 'Remboursement'), ('ontheflight', 'A la volée')], default='cash', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='localsettings',
            name='min_account_allow',
            field=models.BooleanField(default=False, help_text="Lorsque cette option est activée, si le solde n'est pas suffisant, il y a une demande de confirmation lors de l'achat mais il est autorisé. Dans le cas contraire, l'achat est rendu impossible.", verbose_name="Lorsque le solde n'est pas suffisant, autoriser quand même après demande de confirmation ?"),
        ),
        migrations.AlterField(
            model_name='localsettings',
            name='use_messages',
            field=models.BooleanField(default=True, help_text='La fonction messages/actions sert à laisser des messages entre les différentes permanences ou lister des actions à faire.', verbose_name='Utilisation de la fonction messages/actions ?'),
        ),
        migrations.AlterField(
            model_name='localsettings',
            name='use_subscription',
            field=models.BooleanField(default=True, help_text="La fonction adhésion permet de renseigner la cotisation d'adhésion du foyer.", verbose_name="Utilisation de la fonction cotisation d'adhésion ?"),
        ),
    ]
