# Generated by Django 2.1.7 on 2019-03-23 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20190323_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='approstockop',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryop',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approcompteop',
            name='household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Household'),
        ),
        migrations.AlterField(
            model_name='approstockop',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Product'),
        ),
        migrations.AlterField(
            model_name='inventoryop',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Product'),
        ),
    ]
