# Generated by Django 2.2.6 on 2020-03-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20200126_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='activated',
            field=models.BooleanField(default=True, help_text="Une référence non activée n'apparaît pas dans le logiciel. Utilisé pour archiver les produits", verbose_name='activé'),
        ),
    ]
