# Generated by Django 2.1.7 on 2019-03-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20190323_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='localsettings',
            name='mail_admin',
            field=models.EmailField(max_length=254, null=True, verbose_name="Mail de l'admin à qui sont reporté les erreurs du logiciel"),
        ),
        migrations.AddField(
            model_name='localsettings',
            name='txt_home',
            field=models.TextField(blank=True, default='<i>Bienvenu au GASE</i>', verbose_name="Texte de la page d'accueil (doit être donnée en code html)"),
        ),
    ]
