# Generated by Django 2.2.6 on 2020-03-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_product_activated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approcompteop',
            options={'verbose_name': "Opération d'appro de compte"},
        ),
        migrations.AlterModelOptions(
            name='changestockop',
            options={'verbose_name': 'Opération sur le stock'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='purchasedetailop',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='approcompteop',
            name='kind',
            field=models.CharField(choices=[('cash', 'Espèces'), ('cheque', 'Chèque'), ('cancellation', 'Annulation/Correction'), ('repayment', 'Remboursement'), ('ontheflight', 'À la volée')], default='cash', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='on_the_flight',
            field=models.BooleanField(default=False, help_text="Réalise un approvisionnement automatique du montant du panier avant de payer.Cette fonction peut être utilise si l'on autorise le payement à la volée, c'est-à-dire lorsque le client n'a pas besoin d'approvisionner son compte mais paye la juste somme.", verbose_name='Paie à la volée'),
        ),
        migrations.AlterField(
            model_name='household',
            name='subscription',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Montant de la cotisation d'adhésion (en €)", max_digits=10, verbose_name='cotisation'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_of_purchase',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Prix d'achat (en €) à l'unité (kg/L/...)", max_digits=10, verbose_name="prix d'achat"),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text="Prix de vente (en €) à l'unité (kg/L/...)", max_digits=10, verbose_name='prix de vente'),
        ),
    ]
