# Generated by Django 2.1.7 on 2019-03-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20190323_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localsettings',
            name='mail_admin',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Mail de l'admin à qui sont reporté les erreurs du logiciel"),
        ),
    ]
