# Generated by Django 2.2.6 on 2020-04-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20200324_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pwyw',
            field=models.BooleanField(default=False, help_text='Une référence à prix libre peut être achetée au prix que le consommateur le souhaite. Dans ce cas, indiquer un prix indicatif ou 0 dans le Prix de vente.', verbose_name='prix libre'),
        ),
    ]
