# Generated by Django 2.2.6 on 2020-04-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20200405_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='activated',
            field=models.BooleanField(default=True, help_text="Un foyer non activé n'apparaît pas dans le logiciel. Utilisé pour archiver les foyers et ses membres", verbose_name='activé'),
        ),
    ]
