# Generated by Django 2.2.6 on 2020-10-04 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_household_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='localsettings',
            name='activity_board',
            field=models.BooleanField(default=True, help_text="Le tableau des permanences permet de gérer l'inscription des membres pour tenir les permanences. Il s'affiche sur la page d'accueil.", verbose_name='Utiliser le tableau des permanences ?'),
        ),
        migrations.AddField(
            model_name='localsettings',
            name='txt_home2',
            field=models.TextField(blank=True, default='Infos utiles genre :\nlocalisation des clés du GASE\nhoraires des permanences\n...\n(ou rien)', verbose_name="texte en base de la page d'accueil (doit être donnée en texte pur et sera centré)"),
        ),
        migrations.AlterField(
            model_name='localsettings',
            name='txt_home',
            field=models.TextField(blank=True, default='<i>Bienvenu·e au GASE</i><br><br>', verbose_name="texte en haut de la page d'accueil (doit être donnée en code html)"),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('comment', models.TextField(blank=True, max_length=1000, verbose_name='Commentaire')),
                ('volunteer1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer1', to='base.Member', verbose_name='Permanencier 1')),
                ('volunteer2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer2', to='base.Member', verbose_name='Permanencier 2')),
            ],
            options={
                'verbose_name': 'Activité',
            },
        ),
    ]
