# Generated by Django 2.2.6 on 2020-10-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_household_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localsettings',
            name='save_mail',
            field=models.BooleanField(default=False, help_text='Cette fonction permet de sauvegarder les emails envoyés ou en attente.', verbose_name='Utilisation de la fonction de sauvegarde des emails ?'),
        ),
        migrations.AlterField(
            model_name='localsettings',
            name='use_appro_kind',
            field=models.BooleanField(default=False, help_text='La fonction type de paiement permet de sauvegarder le moyen de paiement utilisé.', verbose_name='Utilisation de la fonction type de paiement ?'),
        ),
        migrations.AlterField(
            model_name='localsettings',
            name='use_cost_of_purchase',
            field=models.BooleanField(default=False, help_text="La fonction prix d'achat permet de spécifier un prix d'achat différent du prix de vente.", verbose_name="Utilisation de la fonction prix d'achat ?"),
        ),
        migrations.AlterField(
            model_name='localsettings',
            name='use_exports',
            field=models.BooleanField(default=False, help_text="Exports de l'historique d'achat et de la liste des produits.", verbose_name='Utiliser les exports ?'),
        ),
        migrations.AlterField(
            model_name='localsettings',
            name='use_logo',
            field=models.BooleanField(default=False, help_text='Le fichier de logo doit être placé dans le répertoire base\\static\x08ase et son nom de fichier doit etre logo.png.', verbose_name='Affiche le logo dans la première page ?'),
        ),
        migrations.AlterField(
            model_name='localsettings',
            name='use_messages',
            field=models.BooleanField(default=False, help_text='La fonction messages/actions sert à laisser des messages entre les différentes permanences ou lister des actions à faire.', verbose_name='Utilisation de la fonction messages/actions ?'),
        ),
        migrations.AlterField(
            model_name='localsettings',
            name='use_subscription',
            field=models.BooleanField(default=False, help_text="La fonction adhésion permet de renseigner la cotisation d'adhésion du foyer.", verbose_name="Utilisation de la fonction cotisation d'adhésion ?"),
        ),
    ]
