# Generated by Django 3.1.2 on 2020-10-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20201004_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localsettings',
            name='mail_passwd',
            field=models.CharField(blank=True, default='', help_text="Mot de passe SMTP. Si vide :\xa0n'utilisera pas d'authentification", max_length=100, verbose_name="Mot de passe pour l'envoi des mails."),
        ),
        migrations.AlterField(
            model_name='localsettings',
            name='mail_username',
            field=models.CharField(blank=True, default='', help_text="Utilisateur SMTP, exemple : tata. Si vide :\xa0n'utilisera pas d'authentification", max_length=100, verbose_name="Nom d'utilisateur pour l'envoi des mails."),
        ),
    ]
