# Generated by Django 3.1.2 on 2020-10-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20201004_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localsettings',
            name='mail_host',
            field=models.CharField(default='localhost', help_text='Exemple : smtp.titi.com.', max_length=50, verbose_name="Serveur pour l'envoi des mails. « localhost » pour utiliser le serveur du compteur comme serveur d'envoi."),
        ),
        migrations.AlterField(
            model_name='localsettings',
            name='mail_port',
            field=models.IntegerField(default=25, help_text='Exemple : 25 (sans chiffrement), 465 (chiffrement implicite, SSL), 587 (chiffrement explicite, TLS).', verbose_name="Port smtp pour l'envoi des mails."),
        ),
    ]
