# Generated by Django 3.1.2 on 2020-10-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20201004_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localsettings',
            name='mail_from',
            field=models.CharField(blank=True, default='tata@example.com', help_text='Exemple : tata@titi.com.', max_length=100, verbose_name="Expéditeur pour l'envoi des mails."),
        ),
    ]
