# Generated by Django 2.2.16 on 2020-10-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_initialize_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='account',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='solde de la cagnotte'),
        ),
        migrations.AlterField(
            model_name='household',
            name='name',
            field=models.CharField(help_text='Nom qui apparaitra dans la liste des foyers pour faire ses achats.', max_length=200, verbose_name='nom du foyer'),
        ),
        migrations.AlterField(
            model_name='household',
            name='on_the_flight',
            field=models.BooleanField(default=False, help_text="Réalise un approvisionnement automatique du montant du panier avant de payer.Cette fonction peut être utilise si l'on autorise le payement à la volée, c'est-à-dire lorsque le client n'a pas besoin d'approvisionner sa cagnotte mais paye la juste somme.", verbose_name='Paie à la volée'),
        ),
        migrations.AlterField(
            model_name='localsettings',
            name='mail_protocole',
            field=models.CharField(choices=[('no', 'Pas de chiffrement'), ('tls', 'Utiliser TLS'), ('ssl', 'Utiliser SSL')], default='no', max_length=100, verbose_name="Chiffrement utilisé pour l'envoi de mails."),
        ),
        migrations.AlterField(
            model_name='localsettings',
            name='prefix_object_mail',
            field=models.CharField(blank=True, default='', help_text='Un préfixe est souvent encadré par des crochers, exemples : [GASE].', max_length=15, verbose_name="Préfixe dans l'objet des emails."),
        ),
    ]
