# Generated by Django 2.2.6 on 2020-10-05 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20201004_2157'),
        ('base', '0018_initialize_settings'),
    ]

    operations = [
    ]
