# Generated by Django 2.2.6 on 2020-10-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20201005_2122'),
        ('base', '0019_merge_20201005_2253'),
    ]

    operations = [
    ]
