# Generated by Django 2.2.6 on 2020-10-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_merge_20201012_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-date'], 'verbose_name': 'Activité'},
        ),
        migrations.RenameField(
            model_name='mail',
            old_name='send',
            new_name='sent',
        ),
        migrations.RemoveField(
            model_name='localsettings',
            name='save_mail',
        ),
        migrations.AlterField(
            model_name='mail',
            name='kind',
            field=models.CharField(choices=[('appro_cagnotte', 'approvisionnement de la cagnotte'), ('ticket', 'ticket de caisse'), ('alerte_stock', 'alerte stock'), ('appro_stock', 'approvisionnement stock'), ('notification', 'notification')], default='notification', max_length=20),
        ),
        migrations.RemoveField(
            model_name='mail',
            name='recipients',
        ),
        migrations.AddField(
            model_name='mail',
            name='recipients',
            field=models.ManyToManyField(to='base.Member', verbose_name='Destinataires'),
        ),
    ]
