# Generated by Django 2.2.20 on 2021-04-13 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('base', '0022_activity_required_volounteers'), ('base', '0023_auto_20210409_2032'), ('base', '0024_activity_interested_members'), ('base', '0025_auto_20210409_2043'), ('base', '0026_auto_20210409_2044'), ('base', '0027_auto_20210410_1420'), ('base', '0028_auto_20210410_1740'), ('base', '0029_auto_20210410_1947'), ('base', '0030_auto_20210410_1948'), ('base', '0031_auto_20210410_1951'), ('base', '0032_auto_20210411_1157'), ('base', '0033_localsettings_mail_mailinglist_address'), ('base', '0034_auto_20210412_1454'), ('base', '0035_remove_activity_mailing_status'), ('base', '0036_activity_canceled'), ('base', '0037_localsettings_use_activity_reminders'), ('base', '0038_auto_20210412_2305'), ('base', '0039_auto_20210412_2306')]

    dependencies = [
        ('base', '0021_auto_20201012_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='localsettings',
            name='required_interested_members_default',
            field=models.IntegerField(default=1, help_text="ce nombre est le nombre par défaut proposé lors de l'ajout d'une activité)", verbose_name="Nombre minimum de participants pour qu'une activité puisse se tenir"),
        ),
        migrations.AddField(
            model_name='localsettings',
            name='required_volunteers_default',
            field=models.IntegerField(default=1, help_text="ce nombre est le nombre par défaut proposé lors de l'ajout d'une activité)", verbose_name="Nombre minimum de permanencier pour qu'une activité puisse se tenir"),
        ),
        migrations.AddField(
            model_name='localsettings',
            name='mail_mailinglist_address',
            field=models.CharField(blank=True, default='', help_text="Entrer ici l'adresse email de la mailing list de votre gase cette adresse sera utilisée pour les communications concernant tous les membres (par exemple les rappels d'inscription aux activités)", max_length=100, verbose_name='Adresse de la mailing list du gase'),
        ),
        migrations.AddField(
            model_name='activity',
            name='canceled',
            field=models.BooleanField(default=False, help_text='Est-ce que cette activité est annulée (faute de participant·e·s par exemple)', verbose_name='Annulé'),
        ),
        migrations.AddField(
            model_name='localsettings',
            name='use_activity_reminders',
            field=models.BooleanField(default=False, help_text="Cette fonction permet d'envoyer des relances pour les inscriptions aux activités du gase.", verbose_name='Utilisation de la fonction de relance pour les activités ?'),
        ),
        migrations.AddField(
            model_name='activity',
            name='required_interested_members',
            field=models.IntegerField(default=1, help_text="Nombre de personnes intéressées pour que celle-ci ait lieu. Si > 0 et qu'il n'y a pas assez de personnes intéressées, alors cette activité sera annulée quelques jours avant la date à laquelle elle était prévue.  Mettre 0 ou -1 pour désactiver cette fonctionnalité.", validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de personnes intéressées requises'),
        ),
        migrations.AddField(
            model_name='activity',
            name='interested_members',
            field=models.ManyToManyField(blank=True, help_text="La liste des personnes intéressées permet de déterminer si une activité vaut le coup d'être organisée ou si elle mérite d'être annulée.", to='base.Member', verbose_name='Personnes intéressées'),
        ),
        migrations.AddField(
            model_name='activity',
            name='required_volunteers',
            field=models.IntegerField(default=1, help_text="Il faudra qu'il y ait au moins ce nombre de permanencier·e·s inscrit·e·s pour que cette activité puisse avoir lieu. Si > 0 et qu'il n'y a pas assez de permanencier·e·s, alors cette activité sera annulée quelques jours avant la date à laquelle elle était prévue. Mettre 0 ou -1 pour désactiver cettefonctionnalité.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='Nombre Permanencier·e·s requis'),
        ),
    ]
