# Generated by Django 2.2.18 on 2022-02-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20201012_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localsettings',
            name='use_logo',
            field=models.BooleanField(default=False, help_text='Le fichier de logo doit être placé dans le répertoire base/static/base et son nom de fichier doit etre logo.png.', verbose_name='Affiche le logo dans la première page ?'),
        ),
    ]
