# Generated by Django 3.2.11 on 2023-01-24 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20220206_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='localsettings',
            name='use_categories',
            field=models.BooleanField(default=True, help_text='Si désactivé, les catégories ne seront pas proposées dans le formulaire et dans les listings.', verbose_name='Utilise les catégories de produits'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category', verbose_name='catégorie'),
        ),
    ]
