# Generated by Django 3.2.25 on 2024-11-11 15:23

from django.db import migrations

def fix_base_changestockop_label_typo(apps, schema_editor):
    ChangeStockOp = apps.get_model('base', 'changestockop')
    ChangeStockOp.objects.filter(label='Ivnentaire').update(label="Inventaire")

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20230124_2344'),
    ]

    operations = [
        migrations.RunPython(
            fix_base_changestockop_label_typo,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
