# Generated by Django 3.2.22 on 2024-11-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20230124_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approcompteop',
            options={'verbose_name': "Opération d'appro de cagnotte", 'verbose_name_plural': "Opérations d'appro de cagnotte"},
        ),
    ]
