# Generated by Django 3.2.22 on 2024-11-11 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_approcompteop_options'),
        ('base', '0024_auto_20241111_1623'),
    ]

    operations = [
    ]
