# Generated by Django 3.2.25 on 2025-03-01 14:25

from django.db import migrations, models
import django.db.models.deletion

def kind_to_paymenttype(apps, schema_editor):
    PaymentType = apps.get_model('base', 'PaymentType')
    ApproCompteOp = apps.get_model('base', 'ApproCompteOp')

    CASH = 'cash'
    CHEQUE = 'cheque'
    CANCELLATION = 'cancellation'
    REPAYMENT = 'repayment'
    ONTHEFLIGHT = 'ontheflight'
    KIND_CHOICES = [
        (CASH, 'Espèces'),
        (CHEQUE, 'Chèque'),
        (CANCELLATION, 'Annulation/Correction'),
        (REPAYMENT, 'Remboursement'),
        (ONTHEFLIGHT, 'À la volée'),
    ]

    for op in ApproCompteOp.objects.all():
        for (k1, k2) in KIND_CHOICES:
            if op.kind == k1:
                pt, _ = PaymentType.objects.get_or_create(name=k2)
                op.paymenttype = pt
                op.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_merge_20241111_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Type de paiement',
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='localsettings',
            old_name='use_appro_kind',
            new_name='use_paymenttype',
        ),
        migrations.AddField(
            model_name='approcompteop',
            name='paymenttype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.paymenttype', verbose_name='Type de paiement'),
        ),
        migrations.RunPython(
            kind_to_paymenttype
        ),
        migrations.RemoveField(
            model_name='approcompteop',
            name='kind',
        ),
    ]
