# Generated by Django 3.2.22 on 2025-06-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_localsettings_txt_home'),
        ('base', '0026_auto_20250301_1525'),
    ]

    operations = [
    ]
