# Generated by Django 5.2.8 on 2025-11-28 17:44

from django.db import migrations


def clear_all_sessions(apps, schema_editor):
    # As django.contrib.sessions.serializers.PickleSerializer got removed in Django 5.0
    # DB syntax of sessions has changed. Lets trash everthing !
    Session = apps.get_model('sessions', 'session')
    Session.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_merge_20250622_1430'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            clear_all_sessions, 
            reverse_code=migrations.RunPython.noop,
        )
    ]
