# Generated by Django 3.2.25 on 2025-10-22 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_merge_20250622_1430'),
    ]

    operations = [
        migrations.RenameModel(
            'ApproCompteOp',
            'CagnotteOp'
        ),
    ]
