# Generated by Django 3.2.25 on 2025-10-22 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20251022_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cagnotteop',
            options={'verbose_name': 'Opération sur les cagnottes', 'verbose_name_plural': 'Opérations sur les cagnottes'},
        ),
        migrations.AlterModelOptions(
            name='changestockop',
            options={'verbose_name': 'Opération sur le stock', 'verbose_name_plural': 'Opérations sur le stock'},
        ),
        migrations.AlterField(
            model_name='cagnotteop',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='cagnotteop',
            name='household',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.household', verbose_name='Foyer'),
        ),
    ]
