# Generated by Django 3.2.25 on 2025-10-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20251022_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='cagnotteop',
            name='label',
            field=models.CharField(default='ApproCagnotte', max_length=20),
            preserve_default=False,
        ),
    ]
