# Generated by Django 3.2.25 on 2025-10-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_cagnotteop_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='cagnotteop',
            name='comment',
            field=models.TextField(blank=True, verbose_name='commentaire'),
        ),
    ]
