# Generated by Django 5.2.14 on 2026-05-29 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0028_auto_20251128_1844"),
        ("base", "0031_cagnotteop_comment"),
    ]

    operations = []
