# Generated by Django 5.2.14 on 2026-05-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0032_merge_0028_auto_20251128_1844_0031_cagnotteop_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="referents",
            field=models.ManyToManyField(
                blank=True,
                help_text='Les référent·es reçoivent, si elles ont activé les alertes, un mail à chaque fois qu\'un produit du fournisseur est approvisionné ou que le stock devient plus bas que le niveau "Alerte stock" paramétré sur chaque produit.',
                to="base.member",
                verbose_name="référent·es",
            ),
        ),
    ]
