# Generated by Django 5.2.14 on 2026-05-30 20:45

from django.db import migrations


def init_ref_produits(apps, schema_editor):
    Product = apps.get_model('base', 'product')
    Provider = apps.get_model('base', 'provider')

    for provider in Provider.objects.all():
        # Collect all referents of all active products
        referents = Product.objects.filter(
            activated=True,
            provider=provider,
            referent__isnull=False,
        ).order_by(
            'referent'
        ).values_list(
            'referent',
            flat=True,
        ).distinct()
        # set them on products
        provider.referents.set(referents)


def delete_ref_produits(apps, schema_editor):
    Provider = apps.get_model('base', 'provider')
    for provider in Provider.objects.all():
        provider.referents.clear()


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0033_provider_referents"),
    ]

    operations = [
        migrations.RunPython(init_ref_produits, reverse_code=delete_ref_produits)
    ]

